# Generated by Django 3.2.8 on 2021-10-17 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('customer_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('business_start', models.CharField(max_length=4)),
                ('business_end', models.CharField(max_length=4)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Stuff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('is_supervisor', models.BooleanField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.store')),
                ('stuff_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StoreOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10)),
                ('pick_up_time', models.DateTimeField()),
                ('order_time', models.DateTimeField()),
                ('half_duck', models.IntegerField()),
                ('duck', models.IntegerField()),
                ('source', models.IntegerField()),
                ('wrap', models.IntegerField()),
                ('sides', models.IntegerField()),
                ('combo', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.customer')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.store')),
            ],
            options={
                'managed': True,
            },
        ),
    ]
